[package]
name = "audio-writer-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
cpal = "0.15.3"
anyhow = "1.0.75"
log = "0.4.20"
env_logger = "0.10.1"
hound = "3.5.1"
libc = "0.2.147"
